### PR TITLE
Compiled cleanse

### PR DESCRIPTION
**Pull request by derek-adair**
It is best practice to only commit source code to version control so i've removed/ignored the entire directory of compiled css/js files.  You can still add these to your npm distros but I'd avoid the entire built/ directory.

### CODE REVIEW

**Comment by minimaluminium** [comment]
`built` directory is included intentionally as the monorepo changes are automatically synced with each theme's own repository. If it's excluded, official themes downloaded from the Marketplace won't have those assets.

**Comment by derek-adair** [comment]
I guess I don't understand what necessitates tracking these in any repository.  These should be generated in whatever build steps used to deploy them to the marketplace.  It's 100% going to cause problems for people who access these repositories via github.

**Comment by minimaluminium** [comment]
There's no specific deploy process for the Marketplace, it's rather a simple process behind the scene. When official themes are installed, they're directly downloaded from GitHub which makes the assets in `built` directory required in the theme repos.

**Comment by derek-adair** [comment]
oh ya that would require them to be there!  

Have you all considered the use of github [releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)? It would allow you to adhere to these standards as well as provide the benefit of providing an easy-to-access catalog of these theme's release history among other tangible benefits.

**Pull request closed without merging**
